version: "3.8"
services:
 
  kafka-producer-parser:
    container_name: kafka-producer-parser
    image: lengoo/producer/tmxparser:2.0
    build: 
      context: ../data_extraction
    working_dir: /home/working_dir
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - ../data_extraction:/home/working_dir:cached
  
  kafka-consumer-filter:
    container_name: kafka-consumer-filter
    image: lengoo/consumer/filter:2.0
    build: 
      context: ../data_cleaning
    working_dir: /home/working_dir
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - ../data_cleaning:/home/working_dir:cached
  
networks: 
  default:
    external:
      name: lengoo_mtx